name: client-build

on:
  push:
    branches: [ main ]
    paths:
      - 'client/**'
jobs:
  cache-node-modules:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      id-token: write
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Cache node_modules cache
        id: cache-node
        uses: actions/cache@v4
        with:
          path: |
            client/node_modules
          key: ${{ runner.os }}-node-modules-client-${{ hashFiles('client/yarn.lock') }}
      - name: Install yarn deps
        if: steps.cache-node.outputs.cache-hit != 'true'
        run: |
          cd client
          yarn install --frozen-lockfile
