name: test

on:
  push:
    branches: [ main ]
    paths:
      - '.github/workflows/test.yaml'
jobs:
  build:
    runs-on: windows-2022
    steps:

      - name: Set Short SHA
        shell: bash
        run: echo "SHORT_SHA=${GITHUB_SHA::7}" >> $GITHUB_ENV
      - run: echo $SHORT_SHA